### ISSUE TITLE
No release

### ISSUE THREAD

**Issue by melohagan** [poirazis/bb-component-SuperFieldDatetime#1]
![Screenshot 2024-09-17 at 11 15 03](https://github.com/user-attachments/assets/bf41643a-bcfc-4081-a13d-0224a23279e7)

The release is missing!

Without the release I can't import the plugin:

![Screenshot 2024-09-17 at 11 15 26](https://github.com/user-attachments/assets/3a1911bd-0d1a-4e96-ad6a-b04ac61badcf)

**Comment by poirazis** [comment]
No wonder noone was using this one @melohagan :)
Lacking a release may have played a role.
Fixed.
